# Generated by Django 4.2.5 on 2023-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemons', '0003_yeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
