# Generated by Django 4.2.5 on 2023-09-30 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lemons', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='yeet_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
